version: '3.7'

services:
  postgres:
    image: postgres:10.10-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 15432:5432

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - 8000:80
    volumes:
      - ./api:/app
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres:
